// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using server.Data;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240926134232_CentroStatus")]
    partial class CentroStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("server.Models.CentroCategoria", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CentroCategoria");
                });

            modelBuilder.Entity("server.Models.CentroClasse", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CentroClasse");
                });

            modelBuilder.Entity("server.Models.CentroCusto", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Bloqueado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<long?>("IdCentroCategoria")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IdCentroClasse")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IdCentroDiretoria")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IdCentroEmpresa")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IdCentroFilial")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IdCentroLucro")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("NivelTotal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdCentroCategoria");

                    b.HasIndex("IdCentroClasse");

                    b.HasIndex("IdCentroDiretoria");

                    b.HasIndex("IdCentroEmpresa");

                    b.HasIndex("IdCentroFilial");

                    b.HasIndex("IdCentroLucro");

                    b.ToTable("CentroCusto");
                });

            modelBuilder.Entity("server.Models.CentroCustoLancamento", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IdCentroCusto")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IdContaContabil")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IdExercicio")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IdLancamentoTipo")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ValoresAbril")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ValoresAgosto")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ValoresDezembro")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ValoresFevereiro")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ValoresJaneiro")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ValoresJulho")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ValoresJunho")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ValoresMaio")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ValoresMarco")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ValoresNovembro")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ValoresOutubro")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ValoresSetembro")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdCentroCusto");

                    b.HasIndex("IdContaContabil");

                    b.HasIndex("IdExercicio");

                    b.HasIndex("IdLancamentoTipo");

                    b.ToTable("CentroCustoLancamento");
                });

            modelBuilder.Entity("server.Models.CentroCustoSituacao", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Abril")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Agosto")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Dezembro")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Fevereiro")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IdCentroCusto")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IdCentroCustoUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IdCentroStatus")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IdExercicio")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Janeiro")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Julho")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Junho")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Maio")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Marco")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Novembro")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Outubro")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Setembro")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Abril");

                    b.HasIndex("Agosto");

                    b.HasIndex("Dezembro");

                    b.HasIndex("Fevereiro");

                    b.HasIndex("IdCentroCusto");

                    b.HasIndex("IdCentroCustoUsuario");

                    b.HasIndex("IdCentroStatus");

                    b.HasIndex("IdExercicio");

                    b.HasIndex("Janeiro");

                    b.HasIndex("Julho");

                    b.HasIndex("Junho");

                    b.HasIndex("Maio");

                    b.HasIndex("Marco");

                    b.HasIndex("Novembro");

                    b.HasIndex("Outubro");

                    b.HasIndex("Setembro");

                    b.ToTable("CentroCustoSituacao");
                });

            modelBuilder.Entity("server.Models.CentroCustoUsuario", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<long?>("IdCentroCusto")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Nivel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdCentroCusto");

                    b.ToTable("CentroCustoUsuario");
                });

            modelBuilder.Entity("server.Models.CentroDiretoria", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CentroDiretoria");
                });

            modelBuilder.Entity("server.Models.CentroEmpresa", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeReal")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CentroEmpresa");
                });

            modelBuilder.Entity("server.Models.CentroFilial", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("IdEmpresa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("CentroFilial");
                });

            modelBuilder.Entity("server.Models.CentroLucro", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Bloqueado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("IdCentroCategoria")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IdCentroClasse")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IdCentroDiretoria")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IdCentroEmpresa")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IdCentroFilial")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Imposto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("NivelTotal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Pdd")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdCentroCategoria");

                    b.HasIndex("IdCentroClasse");

                    b.HasIndex("IdCentroDiretoria");

                    b.HasIndex("IdCentroEmpresa");

                    b.HasIndex("IdCentroFilial");

                    b.ToTable("CentroLucro");
                });

            modelBuilder.Entity("server.Models.CentroLucroSituacao", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IdCentroLucro")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IdCentroLucroUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IdCentroStatus")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IdExercicio")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdCentroLucro");

                    b.HasIndex("IdCentroLucroUsuario");

                    b.HasIndex("IdCentroStatus");

                    b.HasIndex("IdExercicio");

                    b.ToTable("CentroLucroSituacao");
                });

            modelBuilder.Entity("server.Models.CentroLucroUsuario", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<long?>("IdCentroLucro")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nivel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdCentroLucro");

                    b.ToTable("CentroLucroUsuario");
                });

            modelBuilder.Entity("server.Models.CentroStatus", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BgColor")
                        .HasColumnType("TEXT");

                    b.Property<long>("Codigo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CentroStatus");
                });

            modelBuilder.Entity("server.Models.ComboInformacoes", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IdCentroCusto")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IdComboInformacoesSeparacao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdCentroCusto");

                    b.HasIndex("IdComboInformacoesSeparacao");

                    b.ToTable("ComboInformacoes");
                });

            modelBuilder.Entity("server.Models.ComboSeparador", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ComboSeparador");
                });

            modelBuilder.Entity("server.Models.ContaContabil", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Codigo")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Digito")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("ExigeJustificativa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Help")
                        .HasColumnType("TEXT");

                    b.Property<long?>("IdContaContabilClassificacao")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IdContaContabilFormula")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Limite")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("NaoAceitaCalculo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Visualizar")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdContaContabilClassificacao");

                    b.HasIndex("IdContaContabilFormula");

                    b.ToTable("ContaContabil");
                });

            modelBuilder.Entity("server.Models.ContaContabilClassificacao", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Codigo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContaContabilClassificacao");
                });

            modelBuilder.Entity("server.Models.ContaContabilFormula", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContaContabilFormula");
                });

            modelBuilder.Entity("server.Models.ContaContabilPrestadores", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContaContabilPrestadores");
                });

            modelBuilder.Entity("server.Models.Exercicio", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aberto")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ano")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Exercicio");
                });

            modelBuilder.Entity("server.Models.Funcionario", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IdCentroCusto")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IdFuncionarioCargo")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IdFuncionarioContratacao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Periculosidade")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PlanoSaudeValor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdCentroCusto");

                    b.HasIndex("IdFuncionarioCargo");

                    b.HasIndex("IdFuncionarioContratacao");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("server.Models.FuncionarioCargo", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FuncionarioCargo");
                });

            modelBuilder.Entity("server.Models.FuncionarioContratacao", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FuncionarioContratacao");
                });

            modelBuilder.Entity("server.Models.FuncionarioDependente", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IdFuncionario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PlanoSaudeValor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdFuncionario");

                    b.ToTable("FuncionarioDependente");
                });

            modelBuilder.Entity("server.Models.LancamentoTipo", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Codigo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LancamentoTipo");
                });

            modelBuilder.Entity("server.Models.Mercado", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mercado");
                });

            modelBuilder.Entity("server.Models.Parametro", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Parametro");
                });

            modelBuilder.Entity("server.Models.Produto", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Custo")
                        .HasColumnType("TEXT");

                    b.Property<long?>("IdCentroFilial")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IdMercado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Linha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdCentroFilial");

                    b.HasIndex("IdMercado");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("server.Shared.ComboBox.ComboBox", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CentroCustoId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CentroCustoId1")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CentroCustoId2")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CentroCustoId3")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CentroCustoId4")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CentroCustoId5")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CentroCustoLancamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CentroCustoLancamentoId1")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CentroCustoLancamentoId2")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CentroCustoLancamentoId3")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CentroCustoSituacaoId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CentroCustoSituacaoId1")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CentroCustoSituacaoId2")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CentroCustoSituacaoId3")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CentroCustoSituacaoId4")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CentroCustoUsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CentroFilialId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CentroLucroId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CentroLucroId1")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CentroLucroId2")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CentroLucroId3")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CentroLucroId4")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CentroLucroSituacaoId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CentroLucroSituacaoId1")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CentroLucroSituacaoId2")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CentroLucroSituacaoId3")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CentroLucroUsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ComboInformacoesId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ComboInformacoesId1")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ContaContabilId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ContaContabilId1")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ContaContabilId2")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FuncionarioDependenteId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FuncionarioId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FuncionarioId1")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FuncionarioId2")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ProdutoId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CentroCustoId");

                    b.HasIndex("CentroCustoId1");

                    b.HasIndex("CentroCustoId2");

                    b.HasIndex("CentroCustoId3");

                    b.HasIndex("CentroCustoId4");

                    b.HasIndex("CentroCustoId5");

                    b.HasIndex("CentroCustoLancamentoId");

                    b.HasIndex("CentroCustoLancamentoId1");

                    b.HasIndex("CentroCustoLancamentoId2");

                    b.HasIndex("CentroCustoLancamentoId3");

                    b.HasIndex("CentroCustoSituacaoId");

                    b.HasIndex("CentroCustoSituacaoId1");

                    b.HasIndex("CentroCustoSituacaoId2");

                    b.HasIndex("CentroCustoSituacaoId3");

                    b.HasIndex("CentroCustoSituacaoId4");

                    b.HasIndex("CentroCustoUsuarioId");

                    b.HasIndex("CentroFilialId");

                    b.HasIndex("CentroLucroId");

                    b.HasIndex("CentroLucroId1");

                    b.HasIndex("CentroLucroId2");

                    b.HasIndex("CentroLucroId3");

                    b.HasIndex("CentroLucroId4");

                    b.HasIndex("CentroLucroSituacaoId");

                    b.HasIndex("CentroLucroSituacaoId1");

                    b.HasIndex("CentroLucroSituacaoId2");

                    b.HasIndex("CentroLucroSituacaoId3");

                    b.HasIndex("CentroLucroUsuarioId");

                    b.HasIndex("ComboInformacoesId");

                    b.HasIndex("ComboInformacoesId1");

                    b.HasIndex("ContaContabilId");

                    b.HasIndex("ContaContabilId1");

                    b.HasIndex("ContaContabilId2");

                    b.HasIndex("FuncionarioDependenteId");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("FuncionarioId1");

                    b.HasIndex("FuncionarioId2");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("ProdutoId1");

                    b.ToTable("ComboBox");
                });

            modelBuilder.Entity("server.Models.CentroCusto", b =>
                {
                    b.HasOne("server.Models.CentroCategoria", "CentroCategoria")
                        .WithMany()
                        .HasForeignKey("IdCentroCategoria");

                    b.HasOne("server.Models.CentroClasse", "CentroClasse")
                        .WithMany()
                        .HasForeignKey("IdCentroClasse");

                    b.HasOne("server.Models.CentroDiretoria", "CentroDiretoria")
                        .WithMany()
                        .HasForeignKey("IdCentroDiretoria");

                    b.HasOne("server.Models.CentroEmpresa", "CentroEmpresa")
                        .WithMany()
                        .HasForeignKey("IdCentroEmpresa");

                    b.HasOne("server.Models.CentroFilial", "CentroFilial")
                        .WithMany()
                        .HasForeignKey("IdCentroFilial");

                    b.HasOne("server.Models.CentroLucro", "CentroLucro")
                        .WithMany()
                        .HasForeignKey("IdCentroLucro");

                    b.Navigation("CentroCategoria");

                    b.Navigation("CentroClasse");

                    b.Navigation("CentroDiretoria");

                    b.Navigation("CentroEmpresa");

                    b.Navigation("CentroFilial");

                    b.Navigation("CentroLucro");
                });

            modelBuilder.Entity("server.Models.CentroCustoLancamento", b =>
                {
                    b.HasOne("server.Models.CentroCusto", "CentroCusto")
                        .WithMany()
                        .HasForeignKey("IdCentroCusto");

                    b.HasOne("server.Models.ContaContabil", "ContaContabil")
                        .WithMany()
                        .HasForeignKey("IdContaContabil");

                    b.HasOne("server.Models.Exercicio", "Exercicio")
                        .WithMany()
                        .HasForeignKey("IdExercicio");

                    b.HasOne("server.Models.LancamentoTipo", "LancamentoTipo")
                        .WithMany()
                        .HasForeignKey("IdLancamentoTipo");

                    b.Navigation("CentroCusto");

                    b.Navigation("ContaContabil");

                    b.Navigation("Exercicio");

                    b.Navigation("LancamentoTipo");
                });

            modelBuilder.Entity("server.Models.CentroCustoSituacao", b =>
                {
                    b.HasOne("server.Models.LancamentoTipo", "LancamentoTipoAbril")
                        .WithMany()
                        .HasForeignKey("Abril");

                    b.HasOne("server.Models.LancamentoTipo", "LancamentoTipoAgosto")
                        .WithMany()
                        .HasForeignKey("Agosto");

                    b.HasOne("server.Models.LancamentoTipo", "LancamentoTipoDezembro")
                        .WithMany()
                        .HasForeignKey("Dezembro");

                    b.HasOne("server.Models.LancamentoTipo", "LancamentoTipoFevereiro")
                        .WithMany()
                        .HasForeignKey("Fevereiro");

                    b.HasOne("server.Models.CentroCusto", "CentroCusto")
                        .WithMany()
                        .HasForeignKey("IdCentroCusto");

                    b.HasOne("server.Models.CentroCustoUsuario", "CentroCustoUsuario")
                        .WithMany()
                        .HasForeignKey("IdCentroCustoUsuario");

                    b.HasOne("server.Models.CentroStatus", "CentroStatu")
                        .WithMany()
                        .HasForeignKey("IdCentroStatus");

                    b.HasOne("server.Models.Exercicio", "Exercicio")
                        .WithMany()
                        .HasForeignKey("IdExercicio");

                    b.HasOne("server.Models.LancamentoTipo", "LancamentoTipoJaneiro")
                        .WithMany()
                        .HasForeignKey("Janeiro");

                    b.HasOne("server.Models.LancamentoTipo", "LancamentoTipoJulho")
                        .WithMany()
                        .HasForeignKey("Julho");

                    b.HasOne("server.Models.LancamentoTipo", "LancamentoTipoJunho")
                        .WithMany()
                        .HasForeignKey("Junho");

                    b.HasOne("server.Models.LancamentoTipo", "LancamentoTipoMaio")
                        .WithMany()
                        .HasForeignKey("Maio");

                    b.HasOne("server.Models.LancamentoTipo", "LancamentoTipoMarco")
                        .WithMany()
                        .HasForeignKey("Marco");

                    b.HasOne("server.Models.LancamentoTipo", "LancamentoTipoNovembro")
                        .WithMany()
                        .HasForeignKey("Novembro");

                    b.HasOne("server.Models.LancamentoTipo", "LancamentoTipoOutubro")
                        .WithMany()
                        .HasForeignKey("Outubro");

                    b.HasOne("server.Models.LancamentoTipo", "LancamentoTipoSetembro")
                        .WithMany()
                        .HasForeignKey("Setembro");

                    b.Navigation("CentroCusto");

                    b.Navigation("CentroCustoUsuario");

                    b.Navigation("CentroStatu");

                    b.Navigation("Exercicio");

                    b.Navigation("LancamentoTipoAbril");

                    b.Navigation("LancamentoTipoAgosto");

                    b.Navigation("LancamentoTipoDezembro");

                    b.Navigation("LancamentoTipoFevereiro");

                    b.Navigation("LancamentoTipoJaneiro");

                    b.Navigation("LancamentoTipoJulho");

                    b.Navigation("LancamentoTipoJunho");

                    b.Navigation("LancamentoTipoMaio");

                    b.Navigation("LancamentoTipoMarco");

                    b.Navigation("LancamentoTipoNovembro");

                    b.Navigation("LancamentoTipoOutubro");

                    b.Navigation("LancamentoTipoSetembro");
                });

            modelBuilder.Entity("server.Models.CentroCustoUsuario", b =>
                {
                    b.HasOne("server.Models.CentroCusto", "CentroCusto")
                        .WithMany()
                        .HasForeignKey("IdCentroCusto");

                    b.Navigation("CentroCusto");
                });

            modelBuilder.Entity("server.Models.CentroFilial", b =>
                {
                    b.HasOne("server.Models.CentroEmpresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("server.Models.CentroLucro", b =>
                {
                    b.HasOne("server.Models.CentroCategoria", "CentroCategoria")
                        .WithMany()
                        .HasForeignKey("IdCentroCategoria");

                    b.HasOne("server.Models.CentroClasse", "CentroClasse")
                        .WithMany()
                        .HasForeignKey("IdCentroClasse");

                    b.HasOne("server.Models.CentroDiretoria", "CentroDiretoria")
                        .WithMany()
                        .HasForeignKey("IdCentroDiretoria");

                    b.HasOne("server.Models.CentroEmpresa", "CentroEmpresa")
                        .WithMany()
                        .HasForeignKey("IdCentroEmpresa");

                    b.HasOne("server.Models.CentroFilial", "CentroFilial")
                        .WithMany()
                        .HasForeignKey("IdCentroFilial");

                    b.Navigation("CentroCategoria");

                    b.Navigation("CentroClasse");

                    b.Navigation("CentroDiretoria");

                    b.Navigation("CentroEmpresa");

                    b.Navigation("CentroFilial");
                });

            modelBuilder.Entity("server.Models.CentroLucroSituacao", b =>
                {
                    b.HasOne("server.Models.CentroLucro", "CentroLucro")
                        .WithMany()
                        .HasForeignKey("IdCentroLucro");

                    b.HasOne("server.Models.CentroLucroUsuario", "CentroLucroUsuario")
                        .WithMany()
                        .HasForeignKey("IdCentroLucroUsuario");

                    b.HasOne("server.Models.CentroStatus", "CentroStatu")
                        .WithMany()
                        .HasForeignKey("IdCentroStatus");

                    b.HasOne("server.Models.Exercicio", "Exercicio")
                        .WithMany()
                        .HasForeignKey("IdExercicio");

                    b.Navigation("CentroLucro");

                    b.Navigation("CentroLucroUsuario");

                    b.Navigation("CentroStatu");

                    b.Navigation("Exercicio");
                });

            modelBuilder.Entity("server.Models.CentroLucroUsuario", b =>
                {
                    b.HasOne("server.Models.CentroLucro", "CentroLucro")
                        .WithMany()
                        .HasForeignKey("IdCentroLucro");

                    b.Navigation("CentroLucro");
                });

            modelBuilder.Entity("server.Models.ComboInformacoes", b =>
                {
                    b.HasOne("server.Models.CentroCusto", "CentroCusto")
                        .WithMany()
                        .HasForeignKey("IdCentroCusto");

                    b.HasOne("server.Models.ComboSeparador", "ComboInformacoesSeparacao")
                        .WithMany()
                        .HasForeignKey("IdComboInformacoesSeparacao");

                    b.Navigation("CentroCusto");

                    b.Navigation("ComboInformacoesSeparacao");
                });

            modelBuilder.Entity("server.Models.ContaContabil", b =>
                {
                    b.HasOne("server.Models.ContaContabilClassificacao", "ContaContabilClassificacao")
                        .WithMany()
                        .HasForeignKey("IdContaContabilClassificacao");

                    b.HasOne("server.Models.ContaContabilFormula", "ContaContabilFormula")
                        .WithMany()
                        .HasForeignKey("IdContaContabilFormula");

                    b.Navigation("ContaContabilClassificacao");

                    b.Navigation("ContaContabilFormula");
                });

            modelBuilder.Entity("server.Models.Funcionario", b =>
                {
                    b.HasOne("server.Models.CentroCusto", "CentroCusto")
                        .WithMany()
                        .HasForeignKey("IdCentroCusto");

                    b.HasOne("server.Models.FuncionarioCargo", "FuncionarioCargo")
                        .WithMany()
                        .HasForeignKey("IdFuncionarioCargo");

                    b.HasOne("server.Models.FuncionarioContratacao", "FuncionarioContratacao")
                        .WithMany()
                        .HasForeignKey("IdFuncionarioContratacao");

                    b.Navigation("CentroCusto");

                    b.Navigation("FuncionarioCargo");

                    b.Navigation("FuncionarioContratacao");
                });

            modelBuilder.Entity("server.Models.FuncionarioDependente", b =>
                {
                    b.HasOne("server.Models.Funcionario", "Funcionario")
                        .WithMany("FuncionariosDependentes")
                        .HasForeignKey("IdFuncionario");

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("server.Models.Produto", b =>
                {
                    b.HasOne("server.Models.CentroFilial", "CentroFilial")
                        .WithMany()
                        .HasForeignKey("IdCentroFilial");

                    b.HasOne("server.Models.Mercado", "Mercado")
                        .WithMany()
                        .HasForeignKey("IdMercado");

                    b.Navigation("CentroFilial");

                    b.Navigation("Mercado");
                });

            modelBuilder.Entity("server.Shared.ComboBox.ComboBox", b =>
                {
                    b.HasOne("server.Models.CentroCusto", null)
                        .WithMany("Categorias")
                        .HasForeignKey("CentroCustoId");

                    b.HasOne("server.Models.CentroCusto", null)
                        .WithMany("Classes")
                        .HasForeignKey("CentroCustoId1");

                    b.HasOne("server.Models.CentroCusto", null)
                        .WithMany("Diretorias")
                        .HasForeignKey("CentroCustoId2");

                    b.HasOne("server.Models.CentroCusto", null)
                        .WithMany("Empresas")
                        .HasForeignKey("CentroCustoId3");

                    b.HasOne("server.Models.CentroCusto", null)
                        .WithMany("Filiais")
                        .HasForeignKey("CentroCustoId4");

                    b.HasOne("server.Models.CentroCusto", null)
                        .WithMany("Lucros")
                        .HasForeignKey("CentroCustoId5");

                    b.HasOne("server.Models.CentroCustoLancamento", null)
                        .WithMany("CentroCustos")
                        .HasForeignKey("CentroCustoLancamentoId");

                    b.HasOne("server.Models.CentroCustoLancamento", null)
                        .WithMany("ContaContabeis")
                        .HasForeignKey("CentroCustoLancamentoId1");

                    b.HasOne("server.Models.CentroCustoLancamento", null)
                        .WithMany("Exercicios")
                        .HasForeignKey("CentroCustoLancamentoId2");

                    b.HasOne("server.Models.CentroCustoLancamento", null)
                        .WithMany("LancamentoTipos")
                        .HasForeignKey("CentroCustoLancamentoId3");

                    b.HasOne("server.Models.CentroCustoSituacao", null)
                        .WithMany("CentroCustoUsuarios")
                        .HasForeignKey("CentroCustoSituacaoId");

                    b.HasOne("server.Models.CentroCustoSituacao", null)
                        .WithMany("CentroCustos")
                        .HasForeignKey("CentroCustoSituacaoId1");

                    b.HasOne("server.Models.CentroCustoSituacao", null)
                        .WithMany("CentroStatus")
                        .HasForeignKey("CentroCustoSituacaoId2");

                    b.HasOne("server.Models.CentroCustoSituacao", null)
                        .WithMany("Exercicios")
                        .HasForeignKey("CentroCustoSituacaoId3");

                    b.HasOne("server.Models.CentroCustoSituacao", null)
                        .WithMany("LancamentoTipos")
                        .HasForeignKey("CentroCustoSituacaoId4");

                    b.HasOne("server.Models.CentroCustoUsuario", null)
                        .WithMany("CentroCustos")
                        .HasForeignKey("CentroCustoUsuarioId");

                    b.HasOne("server.Models.CentroFilial", null)
                        .WithMany("Empresas")
                        .HasForeignKey("CentroFilialId");

                    b.HasOne("server.Models.CentroLucro", null)
                        .WithMany("Categorias")
                        .HasForeignKey("CentroLucroId");

                    b.HasOne("server.Models.CentroLucro", null)
                        .WithMany("Classes")
                        .HasForeignKey("CentroLucroId1");

                    b.HasOne("server.Models.CentroLucro", null)
                        .WithMany("Diretorias")
                        .HasForeignKey("CentroLucroId2");

                    b.HasOne("server.Models.CentroLucro", null)
                        .WithMany("Empresas")
                        .HasForeignKey("CentroLucroId3");

                    b.HasOne("server.Models.CentroLucro", null)
                        .WithMany("Filiais")
                        .HasForeignKey("CentroLucroId4");

                    b.HasOne("server.Models.CentroLucroSituacao", null)
                        .WithMany("CentroLucroUsuarios")
                        .HasForeignKey("CentroLucroSituacaoId");

                    b.HasOne("server.Models.CentroLucroSituacao", null)
                        .WithMany("CentroLucros")
                        .HasForeignKey("CentroLucroSituacaoId1");

                    b.HasOne("server.Models.CentroLucroSituacao", null)
                        .WithMany("CentroStatus")
                        .HasForeignKey("CentroLucroSituacaoId2");

                    b.HasOne("server.Models.CentroLucroSituacao", null)
                        .WithMany("Exercicios")
                        .HasForeignKey("CentroLucroSituacaoId3");

                    b.HasOne("server.Models.CentroLucroUsuario", null)
                        .WithMany("CentroLucros")
                        .HasForeignKey("CentroLucroUsuarioId");

                    b.HasOne("server.Models.ComboInformacoes", null)
                        .WithMany("CentroCustos")
                        .HasForeignKey("ComboInformacoesId");

                    b.HasOne("server.Models.ComboInformacoes", null)
                        .WithMany("ComboInformacoesSeparacoes")
                        .HasForeignKey("ComboInformacoesId1");

                    b.HasOne("server.Models.ContaContabil", null)
                        .WithMany("Classificacao")
                        .HasForeignKey("ContaContabilId");

                    b.HasOne("server.Models.ContaContabil", null)
                        .WithMany("ContaContabeis")
                        .HasForeignKey("ContaContabilId1");

                    b.HasOne("server.Models.ContaContabil", null)
                        .WithMany("Formulas")
                        .HasForeignKey("ContaContabilId2");

                    b.HasOne("server.Models.FuncionarioDependente", null)
                        .WithMany("Funcionarios")
                        .HasForeignKey("FuncionarioDependenteId");

                    b.HasOne("server.Models.Funcionario", null)
                        .WithMany("CentroCustos")
                        .HasForeignKey("FuncionarioId");

                    b.HasOne("server.Models.Funcionario", null)
                        .WithMany("FuncionarioCargos")
                        .HasForeignKey("FuncionarioId1");

                    b.HasOne("server.Models.Funcionario", null)
                        .WithMany("FuncionariosContratacoes")
                        .HasForeignKey("FuncionarioId2");

                    b.HasOne("server.Models.Produto", null)
                        .WithMany("CentroFiliais")
                        .HasForeignKey("ProdutoId");

                    b.HasOne("server.Models.Produto", null)
                        .WithMany("Mercados")
                        .HasForeignKey("ProdutoId1");
                });

            modelBuilder.Entity("server.Models.CentroCusto", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("Classes");

                    b.Navigation("Diretorias");

                    b.Navigation("Empresas");

                    b.Navigation("Filiais");

                    b.Navigation("Lucros");
                });

            modelBuilder.Entity("server.Models.CentroCustoLancamento", b =>
                {
                    b.Navigation("CentroCustos");

                    b.Navigation("ContaContabeis");

                    b.Navigation("Exercicios");

                    b.Navigation("LancamentoTipos");
                });

            modelBuilder.Entity("server.Models.CentroCustoSituacao", b =>
                {
                    b.Navigation("CentroCustoUsuarios");

                    b.Navigation("CentroCustos");

                    b.Navigation("CentroStatus");

                    b.Navigation("Exercicios");

                    b.Navigation("LancamentoTipos");
                });

            modelBuilder.Entity("server.Models.CentroCustoUsuario", b =>
                {
                    b.Navigation("CentroCustos");
                });

            modelBuilder.Entity("server.Models.CentroFilial", b =>
                {
                    b.Navigation("Empresas");
                });

            modelBuilder.Entity("server.Models.CentroLucro", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("Classes");

                    b.Navigation("Diretorias");

                    b.Navigation("Empresas");

                    b.Navigation("Filiais");
                });

            modelBuilder.Entity("server.Models.CentroLucroSituacao", b =>
                {
                    b.Navigation("CentroLucroUsuarios");

                    b.Navigation("CentroLucros");

                    b.Navigation("CentroStatus");

                    b.Navigation("Exercicios");
                });

            modelBuilder.Entity("server.Models.CentroLucroUsuario", b =>
                {
                    b.Navigation("CentroLucros");
                });

            modelBuilder.Entity("server.Models.ComboInformacoes", b =>
                {
                    b.Navigation("CentroCustos");

                    b.Navigation("ComboInformacoesSeparacoes");
                });

            modelBuilder.Entity("server.Models.ContaContabil", b =>
                {
                    b.Navigation("Classificacao");

                    b.Navigation("ContaContabeis");

                    b.Navigation("Formulas");
                });

            modelBuilder.Entity("server.Models.Funcionario", b =>
                {
                    b.Navigation("CentroCustos");

                    b.Navigation("FuncionarioCargos");

                    b.Navigation("FuncionariosContratacoes");

                    b.Navigation("FuncionariosDependentes");
                });

            modelBuilder.Entity("server.Models.FuncionarioDependente", b =>
                {
                    b.Navigation("Funcionarios");
                });

            modelBuilder.Entity("server.Models.Produto", b =>
                {
                    b.Navigation("CentroFiliais");

                    b.Navigation("Mercados");
                });
#pragma warning restore 612, 618
        }
    }
}
